# Conda environment file
name: battdat
channels:
  - defaults
dependencies:
  - python==3.10.*
  - pandoc  # Needed for the

  # For now, use Pip for everything major
  - pip
  - pip:
    # Install jupyter
    - jupyterlab
    - matplotlib
    - -e ..[test,docs]
